### ISSUE TITLE
Date for the spring instance: Monday February 10

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/uppmax_intro_day_1#1]

**Comment by richelbilderbeek** [comment]
![Screenshot from 2024-12-19 08-55-13](https://github.com/user-attachments/assets/3bdb9a34-ba5d-4ffd-bb71-cc1d591e39d0)

Added to the NAISS shared doc and to this course's page!

**Comment by richelbilderbeek** [comment]
![Screenshot from 2024-12-20 08-38-51](https://github.com/user-attachments/assets/11a192fd-baf0-4218-ba30-dd4687f6a41e)

Monday February 10 it is!

**Comment by richelbilderbeek** [comment]
I will close, as it is now in all the right places :-)
